version: '3'
services:
  gekko:
    restart: always
    build: ./gekko
    links:
      - redis
    environment:
     - HOST
     - PORT
    ports: 
      - 5000:5000


  redis:
    image: redis:latest


  python_gekko:
    restart: always
    build: ./python_gekko

