# range of percentaje
entry_percentage = -1
exit_percentage = 1
# num of periods[short_period|long_period]
short_period = 5
long_period = 10
# signals (yes/no) to get signal(short/long)
signal = 'yes'
# trades is the type of cryptocurrency(eth,btc,bcc, etc)
trades = 'btc'
