# Percentage between the MAs for entering and exiting the market
entry_percentage = -1
exit_percentage = 1

# Moving Average parameters.
short_period = 5
long_period = 10

# Signal generation or trading.
# 'yes' will generate the signals.
# 'no' will generate the trades.
signal = 'yes'  
