
# percentage
percentage = 5
# num of long periods
longperiod = 10
# num of short periods
shortperiod = 5
# long, short, nothing 
signal = 'long'
# indicate type of trades
type = 'btc'
# override <yes> or <no>
override = 'yes'